[project]
name = "about-me-ai"
version = "1.0.0"
description = "AI assistant for answering questions about Yasin"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "fastapi[standard]==0.133.*",
    "langchain==1.2.10",
    "langchain-google-genai==4.2.1",
]
